language: python

sudo: true

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

cache:
    directories:
        - $HOME/.data

install:
    - pip install -U pip
    - pip install numpy>=1.15
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
          pip install http://download.pytorch.org/whl/cpu/torch-1.0.0-cp27-cp27mu-linux_x86_64.whl;
      else
          pip install http://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl;
      fi
    - pip install .[test]
    - pip freeze

branches:
    only:
        - master
        - dev

jobs:
    fast_finish: true
    include:
        - python: 2.7
          env: STAGE=examples
          script:
              - CI=1 pytest -vs --cov=pyro --cov-config .coveragerc --stage test_examples --durations 10
        - python: 3.6
          env: STAGE=examples
          script:
              - CI=1 pytest -vs --cov=pyro --cov-config .coveragerc --stage test_examples --durations 10

after_success:
          - bash <(curl -s https://codecov.io/bash)
